

services:
  # บริการสำหรับฐานข้อมูล MySQL
  db:
    image: mysql:8.0 # แนะนำให้ระบุเวอร์ชัน
    container_name: mechubuev-mysql-db
    restart: always
    environment:
    MYSQL_ROOT_PASSWORD: '${DOCKER_MYSQL_ROOT_PASSWORD}'
    MYSQL_DATABASE: '${DOCKER_MYSQL_DATABASE}'
    MYSQL_USER: '${DOCKER_MYSQL_USER}'
    MYSQL_PASSWORD: '${DOCKER_MYSQL_PASSWORD}'
    ports:
      # เปิด Port 3306 ของ Local ให้เชื่อมต่อกับ Port 3306 ใน Container
      - "3306:3306"
    volumes:
      # บันทึกข้อมูลของ Database ลงบนเครื่องของคุณเพื่อไม่ให้ข้อมูลหาย
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: